name: deploy-to-github-pages
run-name: Build and deploy pages site for ${{ github.actor }}

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build:
    permissions:
      contents: write
      pages: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
          ref: main
    - name: Display dotnet version
      run: dotnet --version
    - name: Build site into dist/ folder
      run: dotnet publish blazor-playground.csproj -c:Release -o dist
    - name: Push changes to gh-pages branch
      run: |
        git config --global user.name "GitHub Action"
        git config --global user.email "action@github.com"
        git add dist dist/*                                   # Add only the dist directory
        git stash push dist                                   # Copy dist into a stash
        git fetch
        git checkout gh-pages
        rm -r *                                               # Remove old site
        git stash pop                                         # Should now contain 'dist' folder
        cp -r dist/wwwroot/* .                                # Copy everything inside of dist/wwwroot folder to root dir
        rm -r dist                                            # Remove dist folder since we copied everything out of it
        git add .
        git commit -m "deploy to github pages on $(date +%m/%d/%Y)"
        git push
      
    
    
