name: deploy-to-github-pages
run-name: Build and deploy pages site for ${{ github.actor }}

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build:
    permissions:
      contents: write
      pages: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Display dotnet version
      run: dotnet --version
    - name: Build site into dist/ folder
      run: dotnet publish blazor-playground.csproj -c:Release -o dist
    - name: Push changes to gh-pages branch
      run: |
        git pull
        git config --global user.name "GitHub Action"
        git config --global user.email "action@github.com"
        git add .
        git commit -m "deploy to github pages on $(date +%m/%d/%Y)"
        git subtree push --prefix dist/wwwroot origin gh-pages
      
    
    
